version: '3.8'
services:
  app:
    build: .
    # image: node:lts
    tty: true
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: yarn dev
  storybook:
    build: .
    tty: true
    container_name: storybook
    volumes:
      - ./app:/app
    ports:
      - 6006:6006
    working_dir: /app
    init: true
    command: yarn storybook

